name: sq-community-branch-plugin

services:
  sonarqube:
    depends_on:
      - db
    image: mc1arke/sonarqube-with-community-branch-plugin:${SONARQUBE_VERSION}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        SONARQUBE_VERSION: ${SONARQUBE_VERSION}
        PLUGIN_VERSION: ${PLUGIN_VERSION}
    container_name: sonarqube
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    restart: unless-stopped
  db:
    image: postgres:11
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
  proxy:
    image: sq-nginx:1.26.1
    container_name: nginx
    networks:
      - sonarnet
    build: ./nginx
    ports:
      - 443:${LISTEN_PORT}
    environment:
      - LISTEN_PORT
      - LISTEN_PROTOCOL
      - SSL_CERT
      - SSL_PRIVATE_KEY
    volumes:
      - ./nginx_data/ssl/certificate.crt:/etc/ssl/certificates/server.crt
      - ./nginx_data/ssl/private.key:/etc/ssl/certificates/server.key
      - nginx_data:/var/log/nginx
    depends_on:
      - sonarqube
    restart: unless-stopped

volumes:
  sonarqube_conf:
  sonarqube_data:
  postgresql:
  postgresql_data:
  nginx_data:

networks:
  sonarnet:
